package vistas;

import LIB.FSTexFieldMD;
import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;

/**
 *
 * @author Derek
 */
public class VistaConductor extends javax.swing.JFrame {
    public VistaConductor() {
        initComponents();
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public static JTable getJtblconductor() {
        return jtblconductor;
    }

    public JInternalFrame getJINTFConductores() {
        return JINTFConductores;
    }

    public JButton getBtnagregarconduc() {
        return btnagregarconduc;
    }

    public JButton getBtnagregardestinatario() {
        return btnagregardestinatario;
    }

    public JButton getBtnagregarremi() {
        return btnagregarremi;
    }

    public JButton getBtnconductor() {
        return btnconductor;
    }

    public JButton getBtneliminar() {
        return btneliminar;
    }

    public JButton getBtnlimpiar() {
        return btnlimpiar;
    }

    public JButton getBtnmodificar() {
        return btnmodificar;
    }

    public JButton getBtnregistrar() {
        return btnregistrar;
    }

    public JButton getBtnregresar() {
        return btnregresar;
    }

    public JDateChooser getJdcfechaentregadestina() {
        return jdcfechaentregadestina;
    }

    public JDateChooser getJdcfechaenvioremiten() {
        return jdcfechaenvioremiten;
    }

    public JSpinner getSpnsalarioconduc1() {
        return spnsalarioconduc1;
    }

    public FSTexFieldMD getTxtcedconductor() {
        return txtcedconductor;
    }

    public FSTexFieldMD getTxtceduladestina() {
        return txtceduladestina;
    }

    public FSTexFieldMD getTxtcedularemiten() {
        return txtcedularemiten;
    }

    public FSTexFieldMD getTxtidconductor() {
        return txtidconductor;
    }

    public FSTexFieldMD getTxtiddestinatario() {
        return txtiddestinatario;
    }

    public FSTexFieldMD getTxtidremitente() {
        return txtidremitente;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JINTFConductores = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnagregarconduc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnagregarremi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnagregardestinatario = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblconductor = new javax.swing.JTable();
        txtidconductor = new LIB.FSTexFieldMD();
        txtcedconductor = new LIB.FSTexFieldMD();
        spnsalarioconduc1 = new javax.swing.JSpinner();
        txtiddestinatario = new LIB.FSTexFieldMD();
        txtceduladestina = new LIB.FSTexFieldMD();
        jdcfechaentregadestina = new com.toedter.calendar.JDateChooser();
        jdcfechaenvioremiten = new com.toedter.calendar.JDateChooser();
        txtcedularemiten = new LIB.FSTexFieldMD();
        txtidremitente = new LIB.FSTexFieldMD();
        btnconductor = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        JINTFConductores.setVisible(true);

        jLabel2.setText("ID Conductor:");

        jLabel3.setText("Cedula: ");

        jLabel4.setText("Salario:");

        btnregistrar.setText("Registrar");

        btnmodificar.setText("Modificar");

        btneliminar.setText("Eliminar");

        btnlimpiar.setText("Limpiar");

        btnagregarconduc.setText("Agregar");

        jPanel3.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Remitente");

        jLabel5.setText("ID Remitente:");

        jLabel6.setText("Cedula :");

        jLabel7.setText("Fecha de Envio:");

        btnagregarremi.setText("Agregar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Conductor");

        jLabel8.setText("ID Destinatario:");

        jLabel9.setText("Cedula:");

        jLabel10.setText("Fecha de Entrega:");

        btnagregardestinatario.setText("Agregar");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Destinatario");

        jtblconductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Conductor", "Remitente", "Destinatario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblconductor);

        txtidconductor.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        txtidconductor.setPlaceholder("Conductor");

        txtcedconductor.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        txtcedconductor.setPlaceholder("Cedula");

        spnsalarioconduc1.setModel(new javax.swing.SpinnerNumberModel(250, 250, 1500, 1));

        txtiddestinatario.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        txtiddestinatario.setPlaceholder("Destinatario");

        txtceduladestina.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        txtceduladestina.setPlaceholder("Cedula");

        txtcedularemiten.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtcedularemiten.setPlaceholder("Cedula");

        txtidremitente.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtidremitente.setPlaceholder("Remitente");

        javax.swing.GroupLayout JINTFConductoresLayout = new javax.swing.GroupLayout(JINTFConductores.getContentPane());
        JINTFConductores.getContentPane().setLayout(JINTFConductoresLayout);
        JINTFConductoresLayout.setHorizontalGroup(
            JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(jLabel12))
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtceduladestina, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                                .addComponent(txtiddestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabel13))))
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                                .addComponent(btnregistrar)
                                                .addGap(25, 25, 25)
                                                .addComponent(btnmodificar)
                                                .addGap(39, 39, 39)
                                                .addComponent(btneliminar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnlimpiar))
                                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(251, 251, 251)
                                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnagregardestinatario)
                                                    .addComponent(jLabel10))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jdcfechaentregadestina, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel11))
                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JINTFConductoresLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(37, 37, 37))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JINTFConductoresLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)))
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtidconductor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnsalarioconduc1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtcedconductor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(btnagregarconduc)
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(jdcfechaenvioremiten, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(47, 47, 47)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtidremitente, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(txtcedularemiten, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnagregarremi))))
                            .addComponent(jSeparator1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JINTFConductoresLayout.setVerticalGroup(
            JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3))
                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addComponent(txtidconductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcedconductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnagregarconduc))
                                        .addGap(18, 18, 18)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(spnsalarioconduc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtidremitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(36, 36, 36)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcedularemiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(btnagregarremi))
                                        .addGap(36, 36, 36)
                                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jdcfechaenvioremiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))))
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13)
                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtiddestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtceduladestina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(btnagregardestinatario)))
                            .addGroup(JINTFConductoresLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jdcfechaentregadestina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(JINTFConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnregistrar)
                            .addComponent(btnmodificar)
                            .addComponent(btneliminar)
                            .addComponent(btnlimpiar))
                        .addGap(26, 26, 26))
                    .addGroup(JINTFConductoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Iconos/conductor64.png"))); // NOI18N
        btnconductor.setText("AGREGAR");

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Iconos/salir32.jpg"))); // NOI18N
        btnregresar.setText("Regresar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Iconos/envios.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnregresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnconductor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnconductor)
                        .addGap(54, 54, 54)
                        .addComponent(btnregresar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame JINTFConductores;
    private javax.swing.JButton btnagregarconduc;
    private javax.swing.JButton btnagregardestinatario;
    private javax.swing.JButton btnagregarremi;
    private javax.swing.JButton btnconductor;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdcfechaentregadestina;
    private com.toedter.calendar.JDateChooser jdcfechaenvioremiten;
    public static javax.swing.JTable jtblconductor;
    private javax.swing.JSpinner spnsalarioconduc1;
    private LIB.FSTexFieldMD txtcedconductor;
    private LIB.FSTexFieldMD txtceduladestina;
    private LIB.FSTexFieldMD txtcedularemiten;
    private LIB.FSTexFieldMD txtidconductor;
    private LIB.FSTexFieldMD txtiddestinatario;
    private LIB.FSTexFieldMD txtidremitente;
    // End of variables declaration//GEN-END:variables
}
